error: Closure called just once immediately after it was declared
  --> $DIR/redundant_closure_call.rs:18:5
   |
LL |     i = redun_closure();
   |     ^^^^^^^^^^^^^^^^^^^
   |
   = note: `-D clippy::redundant-closure-call` implied by `-D warnings`

error: Try not to call a closure in the expression where it is declared.
  --> $DIR/redundant_closure_call.rs:7:17
   |
LL |     let mut k = (|m| m + 1)(i);
   |                 ^^^^^^^^^^^^^^

error: Try not to call a closure in the expression where it is declared.
  --> $DIR/redundant_closure_call.rs:9:9
   |
LL |     k = (|a, b| a * b)(1, 5);
   |         ^^^^^^^^^^^^^^^^^^^^

error: aborting due to 3 previous errors

