error: returning an `Err(_)` with the `?` operator
  --> $DIR/try_err.rs:18:9
   |
LL |         Err(err)?;
   |         ^^^^^^^^^ help: try this: `return Err(err)`
   |
note: the lint level is defined here
  --> $DIR/try_err.rs:4:9
   |
LL | #![deny(clippy::try_err)]
   |         ^^^^^^^^^^^^^^^

error: returning an `Err(_)` with the `?` operator
  --> $DIR/try_err.rs:28:9
   |
LL |         Err(err)?;
   |         ^^^^^^^^^ help: try this: `return Err(err.into())`

error: returning an `Err(_)` with the `?` operator
  --> $DIR/try_err.rs:48:17
   |
LL |                 Err(err)?;
   |                 ^^^^^^^^^ help: try this: `return Err(err)`

error: returning an `Err(_)` with the `?` operator
  --> $DIR/try_err.rs:67:17
   |
LL |                 Err(err)?;
   |                 ^^^^^^^^^ help: try this: `return Err(err.into())`

error: returning an `Err(_)` with the `?` operator
  --> $DIR/try_err.rs:86:23
   |
LL |             Err(_) => Err(1)?,
   |                       ^^^^^^^ help: try this: `return Err(1)`
...
LL |     try_validation!(Ok::<_, i32>(5));
   |     --------------------------------- in this macro invocation
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: returning an `Err(_)` with the `?` operator
  --> $DIR/try_err.rs:122:9
   |
LL |         Err(foo!())?;
   |         ^^^^^^^^^^^^ help: try this: `return Err(foo!())`

error: returning an `Err(_)` with the `?` operator
  --> $DIR/try_err.rs:129:9
   |
LL |         Err(io::ErrorKind::WriteZero)?
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try this: `return Poll::Ready(Err(io::ErrorKind::WriteZero.into()))`

error: returning an `Err(_)` with the `?` operator
  --> $DIR/try_err.rs:131:9
   |
LL |         Err(io::Error::new(io::ErrorKind::InvalidInput, "error"))?
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try this: `return Poll::Ready(Err(io::Error::new(io::ErrorKind::InvalidInput, "error")))`

error: returning an `Err(_)` with the `?` operator
  --> $DIR/try_err.rs:139:9
   |
LL |         Err(io::ErrorKind::NotFound)?
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try this: `return Poll::Ready(Some(Err(io::ErrorKind::NotFound.into())))`

error: aborting due to 9 previous errors

